- hosts: localhost
  connection: local 
  become: true
  tasks: 
    - name: Install nginx
      apt:
        name: nginx
        state: latest
    - name: Start the service
      service:
        name: nginx
        state: started
